export const DIFFICULTY = {
  easy: {
    label: '쉬움',
    description: '처음이라면 여기서 시작',
    stars: 1,
    basePower: 32,
    powerVariance: 10,
    reactionDelay: 0.8,
    surgeChance: 0.04,
    surgePower: 20,
    adaptRate: 0.3,
    mistakeChance: 0.08,
    holdChance: 0,
    threeStepResponse: 0,
    waveAttack: false,
  },
  normal: {
    label: '보통',
    description: '적당한 긴장감',
    stars: 2,
    basePower: 48,
    powerVariance: 8,
    reactionDelay: 0.3,
    surgeChance: 0.08,
    surgePower: 30,
    adaptRate: 0.6,
    mistakeChance: 0.02,
    holdChance: 0.3,
    threeStepResponse: 0.5,
    waveAttack: true,
    wavePeriod: 10,
    wavePeakPower: 75,
    waveDuration: 3,
  },
  hard: {
    label: '어려움',
    description: '생존할 수 있을까?',
    stars: 3,
    basePower: 62,
    powerVariance: 6,
    reactionDelay: 0.1,
    surgeChance: 0.12,
    surgePower: 40,
    adaptRate: 0.9,
    mistakeChance: 0.003,
    holdChance: 0.6,
    threeStepResponse: 0.9,
    waveAttack: true,
    wavePeriod: 7,
    waveDuration: 3.5,
    wavePeakPower: 90,
  },
};
